spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Bia8ha77%
    url: jdbc:mysql://localhost:3306/ticketsystemapi?autoReconnect=TRUE&useSSL=FALSE
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #      javax:
      #        persistence:
      #          schema-generation:
      #            create-source: metadata
      #            scripts:
      #              create-target: script.sql
      #              action: create

    hibernate:
      ddl-auto: update
      highlight_sql: true
      format_sql: true
logging:
  level:
    root: ERROR

